# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primera_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(240, 320)
        self.titulo = QtWidgets.QLabel(Form)
        self.titulo.setGeometry(QtCore.QRect(60, 10, 131, 19))
        self.titulo.setObjectName("titulo")
        self.contador = QtWidgets.QLabel(Form)
        self.contador.setGeometry(QtCore.QRect(60, 40, 121, 71))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.contador.setFont(font)
        self.contador.setFrameShape(QtWidgets.QFrame.Box)
        self.contador.setAlignment(QtCore.Qt.AlignCenter)
        self.contador.setObjectName("contador")
        self.btnClick = QtWidgets.QPushButton(Form)
        self.btnClick.setGeometry(QtCore.QRect(60, 130, 112, 34))
        self.btnClick.setObjectName("btnClick")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(70, 180, 91, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/cocacola.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Contador de clicks"))
        self.titulo.setText(_translate("Form", "Contador de clicks"))
        self.contador.setText(_translate("Form", "0"))
        self.btnClick.setText(_translate("Form", "Haz click aquí"))

from images import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
