# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formulario.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 279)
        MainWindow.setMinimumSize(QtCore.QSize(144, 0))
        MainWindow.setMaximumSize(QtCore.QSize(500, 279))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lblNombre = QtWidgets.QLabel(self.frame)
        self.lblNombre.setObjectName("lblNombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblNombre)
        self.lblApellido = QtWidgets.QLabel(self.frame)
        self.lblApellido.setObjectName("lblApellido")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblApellido)
        self.lblDireccion = QtWidgets.QLabel(self.frame)
        self.lblDireccion.setObjectName("lblDireccion")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lblDireccion)
        self.lblTel = QtWidgets.QLabel(self.frame)
        self.lblTel.setObjectName("lblTel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lblTel)
        self.lblEdad = QtWidgets.QLabel(self.frame)
        self.lblEdad.setObjectName("lblEdad")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lblEdad)
        self.lineNombre = QtWidgets.QLineEdit(self.frame)
        self.lineNombre.setMaxLength(40)
        self.lineNombre.setClearButtonEnabled(True)
        self.lineNombre.setObjectName("lineNombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineNombre)
        self.lineApellido = QtWidgets.QLineEdit(self.frame)
        self.lineApellido.setMaxLength(50)
        self.lineApellido.setClearButtonEnabled(True)
        self.lineApellido.setObjectName("lineApellido")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineApellido)
        self.lineDireccion = QtWidgets.QLineEdit(self.frame)
        self.lineDireccion.setMaxLength(120)
        self.lineDireccion.setClearButtonEnabled(True)
        self.lineDireccion.setObjectName("lineDireccion")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineDireccion)
        self.lineTel = QtWidgets.QLineEdit(self.frame)
        self.lineTel.setMaxLength(30)
        self.lineTel.setClearButtonEnabled(True)
        self.lineTel.setObjectName("lineTel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineTel)
        self.spinEdad = QtWidgets.QSpinBox(self.frame)
        self.spinEdad.setMinimum(17)
        self.spinEdad.setMaximum(100)
        self.spinEdad.setObjectName("spinEdad")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinEdad)
        self.btnRegistrarse = QtWidgets.QPushButton(self.frame)
        self.btnRegistrarse.setObjectName("btnRegistrarse")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.btnRegistrarse)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Registro"))
        self.groupBox.setTitle(_translate("MainWindow", "Formulario de registro"))
        self.lblNombre.setText(_translate("MainWindow", "Nombres"))
        self.lblApellido.setText(_translate("MainWindow", "Apellidos"))
        self.lblDireccion.setText(_translate("MainWindow", "Dirección"))
        self.lblTel.setText(_translate("MainWindow", "Teléfono"))
        self.lblEdad.setText(_translate("MainWindow", "Edad"))
        self.lineNombre.setPlaceholderText(_translate("MainWindow", "Ingresa tu nombre"))
        self.lineApellido.setPlaceholderText(_translate("MainWindow", "Ingresa tu apellido"))
        self.lineDireccion.setPlaceholderText(_translate("MainWindow", "Ingresa tu dirección"))
        self.lineTel.setPlaceholderText(_translate("MainWindow", "Ingresa tu número de teléfono"))
        self.spinEdad.setSpecialValueText(_translate("MainWindow", "Ingresa tu edad (solo mayores de 18)"))
        self.btnRegistrarse.setText(_translate("MainWindow", "Registrarse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
